name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests with Gradle
        run: ./gradlew testDebugUnitTest

      - name: Run app debug unit tests
        run: ./gradlew :app:testDebugUnitTest

      - name: Run app release unit tests
        run: ./gradlew :app:testReleaseUnitTest

      - name: Run apptoolkit debug unit tests
        run: ./gradlew :apptoolkit:testDebugUnitTest

      - name: Run apptoolkit release unit tests
        run: ./gradlew :apptoolkit:testReleaseUnitTest

      - name: Run app test task
        run: ./gradlew :app:test

      - name: Run apptoolkit test task
        run: ./gradlew :apptoolkit:test

      - name: Run Gradle test task
        run: ./gradlew test